version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::153181783728:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-NHfblc8UXSdP"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::153181783728:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-Sk9nECdEzB0f"
cloudformation_execution_role = "arn:aws:iam::153181783728:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-dw4G8Jmiz038"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-egkdkxbyjs5e"
image_repository = ""
region = "us-west-2"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::153181783728:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-cKcNpa36lKRN"
cloudformation_execution_role = "arn:aws:iam::153181783728:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-wk8HOQY8ea6X"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-9ohh0bummnq0"
image_repository = ""
region = "us-west-2"
